### PR TITLE
213 fix z fighting

### LINKED ISSUE #213: Fix Billboard z-fighting
Because the plane of the billboard for displaying points and the test have the same render order, we get z-fighting on the billboard. Explicitly set the text to be rendered last to prevent z-fighting

### PR DESCRIPTION
**Pull request by matthew-buglass**
Closes #213 

# What was the issue
- Previously, our billboard text for data point summaries looked like it was flashing and was bordering on seizure-inducing.
- Turns out the flashing was z-fighting between the text and background. This is because the text and backboard were being rendered in the same space, so the engine couldn't figure out which one to show at a given time. This is what lead to the flickering.

# What was done and why
- Set an offset on the text to move it closer to the user so it would be rendered in front of the user

# How it was tested
- Deployed the fixed to a preview site
- Launched into VR on the Oculus and ensured the text displayed correctly
- NOTE: These screenshots were taken with Aesha's new colour scheme, but for the PR I removed those to keep the work seperate. It does still work with the old colour way.

image

[![video]](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/assets/60230689/52f9173b-0ee9-46e8-a5ba-9deb805a94f2)

### CODE REVIEW

File: my-webxr-app/src/components/DataPointMenu.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default function DataPointMenu(
   return (
     <Billboard visible={selectedDataPoint != null} {...billboardProps}>
       <Plane args={[1.25, 0.8]}>
-        <Text fontSize={0.075} color="black">
+        <Text fontSize={0.075} color="black" depthOffset={-4}>
```
Comment (trangnguyen3010) [inline my-webxr-app/src/components/DataPointMenu.tsx:21]: is the smaller the offset, the closer the text is to the user?
is there any particular reason for value -4? or does it just work?

**Review by trangnguyen3010 — APPROVED** [review]

File: my-webxr-app/src/components/DataPointMenu.tsx (hunk 1 above)
Comment (trangnguyen3010) [reply my-webxr-app/src/components/DataPointMenu.tsx:21]: btw, good catch on the depthOffset! :))

**Review by Aesha7 — APPROVED** [review]
Looks great to me! Thanks for the fix :)

File: my-webxr-app/src/components/DataPointMenu.tsx (hunk 1 above)
Comment (Aesha7) [reply my-webxr-app/src/components/DataPointMenu.tsx:21]: > is the smaller the offset, the closer the text is to the user? is there any particular reason for value -4? or does it just work?

I'm wondering the same...

**Review by Jesster2829 — APPROVED** [review]
after looking at the vast changes of code and making sure i dont get lost, I can say, it does look good

File: my-webxr-app/src/components/DataPointMenu.tsx (hunk 1 above)
Comment (matthew-buglass) [reply my-webxr-app/src/components/DataPointMenu.tsx:22]: 1. Yes, the smaller the number the closer it is to the observer. I added a comment to record that.
2. I chose -4 because I slowly decreased it until everything looked steady. in the 0 to -3 range, there were still a few viewing angles that flickered.

**Comment by Subzeero** [comment]
Nice work!
