### PR TITLE
147 refactor csv reader

### LINKED ISSUE #147: Refactor CSV reader
1. Handle error exception when the user loads an empty link.
2. Fix code redundant in files system CSV reader and URL CSV reader

### PR DESCRIPTION
**Pull request by LongQuanNguyen**
Closes #147 

# What was the issue
Refactor LocalUrlReader and UrlCsvReader.

# What was done and why
1. Refactor duplicate code in LocalUrlReader and UrlCsvReader.

- All the render in LocalUrlReader and UrlCsvReader are now in a single csvReader.tsx under src/components
- All the logic functions (handle parse data, check and open indexedDB) are now in a single csvUtils.tsx under src/utils
- CSV now gets parsed in batch of rows.

2. Handle and catch exceptions in URL when user enters an empty URL. 
3. Use Promise.all() to employ concurrency read/write and optimize performance, thanks @Subzeero for pointing out.

# How it was tested
Automatic unit test

### CODE REVIEW

**Review by Subzeero — COMMENTED** [review]
Looks pretty good at first glance. Do we need to have separate unit tests for the Local/Url CsvReaders, or are the DependentCsvReader tests sufficient? Would these be Gherkins potentially?

**Comment by LongQuanNguyen** [comment]
> Looks pretty good at first glance. Do we need to have separate unit tests for the Local/Url CsvReaders, or are the DependentCsvReader tests sufficient? Would these be Gherkins potentially?

I will try to come up with the new unit test for the readers. I split the readers in the first place so that i could write test for them 🥹

File: my-webxr-app/src/components/DependentCsvReader.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+/**
+ * Handles the parsed data from a CSV file and stores it in a database.
+ *
+ * @param {any} results - The results object returned by Papa.parse. The object data should be an array.
+ * @param {string} dbName - The name of the database where the data should be stored.
+ * @param {string} storeName - The name of the store within the database where the data should be stored.
+ * @throws {Error} Will throw an error if the 'data' property of the results object is not an array.
+ */
+export const handleParsedData = async (results: any, dbName: string, storeName: string) => {
```
[the remark this answers is not in the document]
Comment (LongQuanNguyen) [reply my-webxr-app/src/components/DependentCsvReader.tsx:28]: Thanks for pointing out, I will define an interface for a row data and pass in as `Papa.ParseResult<RowDtata>`. As unknown type may get into more type trouble down in the promises and transactions.

**Comment by LongQuanNguyen** [comment]
> > Looks pretty good at first glance. Do we need to have separate unit tests for the Local/Url CsvReaders, or are the DependentCsvReader tests sufficient? Would these be Gherkins potentially?
> 
> I will try to come up with the new unit test for the readers. I split the readers in the first place so that i could write test for them 🥹

I was try to simulate click and test the return message and parsed data, but this required jsdom env to run on. May be Gherkins for unit test hic

**Review by matthew-buglass — CHANGES_REQUESTED** [review]
A few general things:
- I think all the CSV stuff can be defined in a single file
 - General thoughts on structure
```
my-webxr-app
|- src
   |- components
      |- csvReader.tsx (defines LocalCSVReader and UrlCSVReader. Any actual display things and DOM elements.)
   |- utils
      |- csvUtils.tsx (defines utility functions that the readers use)
```
- File names should be camel case
- Abstract the meat of csv parsing into functions that we can easily test
- Look at making the Reader dom elements react component classes with different reader functions

**Comment by LongQuanNguyen** [comment]
> A few general things:
> 
> * I think all the CSV stuff can be defined in a single file
> * General thoughts on structure
> 
> ```
> my-webxr-app
> |- src
>    |- components
>       |- csvReaders.tsx (defines LocalCSVReader and UrlCSVReader. Any actual display things and DOM elements.)
>    |- utils
>       |- csvUtils.tsx (defines utility functions that the readers use)
> ```
> 
> * File names should be camel case
> * Abstract the meat of csv parsing into functions that we can easily test
> * Look at making the Reader dom elements react component classes with different reader functions

Fixed, thanks so much.

File: my-webxr-app/src/utils/assert.tsx
Comment (matthew-buglass) [inline my-webxr-app/src/utils/assert.tsx:1]: We can remove this and use the `assert.equal()` syntax that Trang has in her PR

File: my-webxr-app/src/utils/csvUtils.tsx [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+ *
+ * @param {string} dbName - The name of the database to validate.
+ * @param {string} storeName - The name of the store to validate.
+ * @throws {Error} Will throw an error if the database does not exist, or if the store does not exist within the
+ * database.
+ */
+export const validateDbAndStore = async (dbName: string, storeName: string) => {
+    const db = await openDB(dbName, 1);
+    const dbExists = db !== undefined;
+    assert(dbExists, `Database "${dbName}" does not exist`);
```
Comment (matthew-buglass) [inline my-webxr-app/src/utils/csvUtils.tsx:17]: `assert.equal()`

File: my-webxr-app/src/utils/csvUtils.tsx [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    const storeExists = db.objectStoreNames.contains(storeName);
+    assert(storeExists, `Store "${storeName}" does not exist in database "${dbName}"`);
```
Comment (matthew-buglass) [inline my-webxr-app/src/utils/csvUtils.tsx:19]: `assert.equal()`

File: my-webxr-app/tests/csvUtils.test.tsx [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+//         const setMessage = jest.fn();
+//
+//         await parseAndHandleLocalCsv(file, dbName, storeName, setMessage);
+//
+//         expect(Papa.parse).toHaveBeenCalledWith(file, expect.objectContaining({
+//             dynamicTyping: true,
+//             complete: expect.any(Function),
+//         }));
+//     });
+// });
```
Comment (matthew-buglass) [inline my-webxr-app/tests/csvUtils.test.tsx:78]: What's the deal here?

**Review by matthew-buglass — CHANGES_REQUESTED** [review]
Looks much nicer now! We just need to change those asserts that we did incorrectly, and I'm suspicious of the big commented-out test.

I would also like to see some descriptions of your tests where you launch the app and tried importing from URLs and local CSVs to make sure the old behaviour is maintained

File: my-webxr-app/tests/csvUtils.test.tsx (hunk 4 above)
Comment (LongQuanNguyen) [reply my-webxr-app/tests/csvUtils.test.tsx:78]: T̶e̶s̶t̶ n̶o̶t̶ p̶a̶s̶s̶ s̶o̶ I̶ c̶o̶m̶m̶e̶n̶t̶e̶d̶ i̶t̶ o̶u̶t̶. I want to test if the arguments are passed correctly to papaparse. In this case, a file is passed as an argument and so I need to use a File constructor. This File constructor is available in the environment of NodeJS version 20 but version 18. Therefore, this test case will fail on CDCI when run with Node18x.

File: my-webxr-app/tests/CsvUtils.test.tsx [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+//         const setMessage = jest.fn();
+//
+//         await parseAndHandleLocalCsv(file, dbName, storeName, setMessage);
+//
+//         expect(Papa.parse).toHaveBeenCalledWith(file, expect.objectContaining({
+//             dynamicTyping: true,
+//             complete: expect.any(Function),
+//         }));
+//     });
+// });
```
Comment (Subzeero) [inline my-webxr-app/tests/CsvUtils.test.tsx:108]: Since `File` wasn't added to Node until v20, could you use a `ReadableStream` instead? I was looking into it here: https://www.npmjs.com/package/papaparse#papa-parse-for-node

**Review by Subzeero — APPROVED** [review]
Nice, it looks like you made ESLint happy! I left a comment about the one test that was failing in Node v20. Let me know what you think.

File: my-webxr-app/tests/CsvUtils.test.tsx (hunk 5 above)
Comment (LongQuanNguyen) [reply my-webxr-app/tests/CsvUtils.test.tsx:108]: I will take a look. I was hopelessly mocking a File and it is painful. Thanks much

Comment (LongQuanNguyen) [reply my-webxr-app/tests/CsvUtils.test.tsx:108]: maybe not, cuz I want to pass in a file, which eventually gets parsed in chunks. If I use readbleStream here I will get type errors unless I modify the parseAndHandleLocalCsv() signature to take a stream of string instead of a file.

What ya thinks?

Comment (Subzeero) [reply my-webxr-app/tests/CsvUtils.test.tsx:108]: Could it take both types? If it's not feasible that's fine; I was just thinking about trying to make the test work for both versions.

File: my-webxr-app/src/utils/csvUtils.tsx (hunk 3 above)
Comment (LongQuanNguyen) [reply my-webxr-app/src/utils/csvUtils.tsx]: i will leave the assert as it it rn.

File: my-webxr-app/src/utils/csvUtils.tsx (hunk 2 above)
Comment (LongQuanNguyen) [reply my-webxr-app/src/utils/csvUtils.tsx]: i will leave the assert as it it rn.

File: my-webxr-app/src/utils/assert.tsx
Comment (LongQuanNguyen) [reply my-webxr-app/src/utils/assert.tsx:1]: assert.equal() will not work so I won't change it here, as confirmed by Trang and Jesse

File: my-webxr-app/tests/CsvUtils.test.tsx
Comment (matthew-buglass) [inline my-webxr-app/tests/CsvUtils.test.tsx:1]: I think this is okay for now, but once we get the DAL implemented we'll need to beef up these tests.

File: my-webxr-app/tests/CsvUtils.test.tsx (hunk 5 above)
Comment (matthew-buglass) [inline my-webxr-app/tests/CsvUtils.test.tsx:108]: If the test is dead, it shouldn't go in.

**Review by matthew-buglass — CHANGES_REQUESTED** [review]
The refactor looks good, nice and clean. Our tests could use some beefing up, but these seem good for the scope of the card. We do need that commented-out test removed.

File: my-webxr-app/tests/CsvUtils.test.tsx
Comment (LongQuanNguyen) [reply my-webxr-app/tests/CsvUtils.test.tsx:1]: affirmative

**Review by matthew-buglass — APPROVED** [review]
